import React, { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppBar, Container, Stack, Toolbar } from "@mui/material";

import ThemeRegistry from "./ThemeRegistry";
import ThemeBtn from "@/components/ThemeBtn";
import MyProfileBtn from "@/components/MyProfileBtn";
import TitleBar from "@/components/TitleBar";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "MFP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html suppressHydrationWarning lang="ko" className={inter.className}>
      <body>
        <ThemeRegistry>
          <TitleBar />
          <AppBar
            sx={{
              minWidth: "10px",
              width: "fit-content",
              right: 0,
              position: "fixed",
              borderBottomLeftRadius: "35px",
              borderWidth: "1px",
            }}
          >
            <Toolbar disableGutters sx={{ padding: "0 10px" }}>
              <Stack
                direction="row"
                spacing={2}
                justifyContent="center"
                alignItems="center"
              >
                <ThemeBtn />
                <MyProfileBtn />
              </Stack>
            </Toolbar>
          </AppBar>
          <Container>{children}</Container>
        </ThemeRegistry>
      </body>
    </html>
  );
}
